import type { TreeSitterLanguage } from "../tree-sitter";

export interface LanguageShape {
  containers: ReadonlySet<string>;
  functions: ReadonlySet<string>;
  variables: ReadonlySet<string>;
  moduleUnits?: ReadonlySet<string>;
  /**
   * Node types that carry the outline of a hierarchical document format. Only
   * the outermost occurrences become units, so nested leaves stay inside the
   * section that owns them instead of turning into one card per scalar.
   */
  sections?: ReadonlySet<string>;
  /**
   * Marks a format that is read as one document rather than as a set of
   * declarations, so it never reaches declaration extraction at all.
   */
  reviewsWholeFile?: boolean;
  /**
   * Marks a language that writes one definition as a run of same-named
   * declarations — a type signature and the equations under it — rather than
   * allowing two of that name to be different things.
   */
  clausesShareOneDeclaration?: boolean;
  imports: ReadonlySet<string>;
  comments: ReadonlySet<string>;
  identifierTypes: ReadonlySet<string>;
  bodyTypes: ReadonlySet<string>;
}
/** Creates an immutable-by-convention syntax-node type set. */
const set = (...values: string[]) => new Set(values);

export const commonIdentifiers = set(
  "atom",
  "class_name",
  "constructor",
  "field_name",
  "identifier",
  "id",
  "long_identifier",
  "lower_case_identifier",
  "message_name",
  "module_identifier",
  "module_name",
  "name",
  "type_identifier",
  "type_name",
  "field_identifier",
  "function_name",
  "namespace_identifier",
  "constant",
  "simple_identifier",
  "simple_name",
  "symbol",
  "sym_name",
  "upper_case_identifier",
  "value_identifier",
  "value_name",
  "variable",
  "variable_name",
  "word",
);

/**
 * The shape of a format that stores data rather than behaviour.
 *
 * A key in a manifest, a job in a workflow, a table in a lock file: none of
 * them carry meaning apart from the document that surrounds them, and none can
 * be confirmed without reading it. Splitting such a file into a card per field
 * therefore asks for many sign-offs on one decision, and turns a generated
 * manifest into hundreds of them. These formats declare no reviewable
 * constructs, so the file itself is the unit.
 */
const dataDocumentShape = {
  containers: set(),
  functions: set(),
  variables: set(),
  imports: set(),
  comments: set(),
  identifierTypes: commonIdentifiers,
  bodyTypes: set(),
  reviewsWholeFile: true,
} satisfies LanguageShape;

export const shapes: Record<TreeSitterLanguage, LanguageShape> = {
  javascript: {
    containers: set(
      "class_declaration",
      "abstract_class_declaration",
      "interface_declaration",
      "type_alias_declaration",
      "enum_declaration",
    ),
    functions: set(
      "function_declaration",
      "generator_function_declaration",
      "function_signature",
      "method_definition",
      "abstract_method_signature",
      "method_signature",
    ),
    variables: set(
      "lexical_declaration",
      "variable_declaration",
      "public_field_definition",
      "field_definition",
      "required_parameter",
      "optional_parameter",
    ),
    imports: set("import_statement"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("class_body", "statement_block", "object_type"),
  },
  typescript: {
    containers: set(
      "class_declaration",
      "abstract_class_declaration",
      "interface_declaration",
      "type_alias_declaration",
      "enum_declaration",
      "internal_module",
    ),
    functions: set(
      "function_declaration",
      "generator_function_declaration",
      "function_signature",
      "method_definition",
      "abstract_method_signature",
      "method_signature",
    ),
    variables: set(
      "lexical_declaration",
      "variable_declaration",
      "public_field_definition",
    ),
    imports: set("import_statement"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("class_body", "statement_block", "object_type", "enum_body"),
  },
  python: {
    containers: set("class_definition"),
    functions: set("function_definition"),
    variables: set("expression_statement", "type_alias_statement"),
    imports: set(
      "import_statement",
      "import_from_statement",
      "future_import_statement",
    ),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("block"),
  },
  java: {
    containers: set(
      "class_declaration",
      "interface_declaration",
      "enum_declaration",
      "record_declaration",
      "annotation_type_declaration",
    ),
    functions: set(
      "method_declaration",
      "constructor_declaration",
      "compact_constructor_declaration",
      "annotation_type_element_declaration",
    ),
    variables: set(
      "field_declaration",
      "constant_declaration",
      "enum_constant",
      "record_component",
    ),
    moduleUnits: set("static_initializer", "block"),
    imports: set("package_declaration", "import_declaration"),
    comments: set("line_comment", "block_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set(
      "class_body",
      "interface_body",
      "enum_body",
      "constructor_body",
      "block",
    ),
  },
  csharp: {
    containers: set(
      "class_declaration",
      "interface_declaration",
      "struct_declaration",
      "record_declaration",
      "enum_declaration",
    ),
    functions: set(
      "method_declaration",
      "constructor_declaration",
      "destructor_declaration",
      "operator_declaration",
      "conversion_operator_declaration",
      "local_function_statement",
      "delegate_declaration",
    ),
    variables: set(
      "field_declaration",
      "property_declaration",
      "event_field_declaration",
      "enum_member_declaration",
    ),
    moduleUnits: set("global_statement"),
    imports: set("using_directive", "extern_alias_directive"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("declaration_list", "block", "enum_member_declaration_list"),
  },
  cpp: {
    containers: set(
      "class_specifier",
      "struct_specifier",
      "union_specifier",
      "enum_specifier",
      "concept_definition",
      "type_definition",
      "alias_declaration",
    ),
    functions: set("function_definition"),
    variables: set(
      "declaration",
      "field_declaration",
      "enumerator",
      "preproc_def",
      "preproc_function_def",
    ),
    imports: set(
      "preproc_include",
      "preproc_call",
      "module_declaration",
      "import_declaration",
      "namespace_alias_definition",
    ),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set(
      "field_declaration_list",
      "compound_statement",
      "enumerator_list",
    ),
  },
  php: {
    containers: set(
      "class_declaration",
      "interface_declaration",
      "trait_declaration",
      "enum_declaration",
    ),
    functions: set("function_definition", "method_declaration"),
    variables: set(
      "property_declaration",
      "property_promotion_parameter",
      "const_declaration",
      "enum_case",
      "expression_statement",
    ),
    imports: set(
      "declare_statement",
      "namespace_use_declaration",
      "namespace_name",
      "php_tag",
      "text",
    ),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set(
      "declaration_list",
      "compound_statement",
      "enum_declaration_list",
    ),
  },
  shell: {
    containers: set(),
    functions: set("function_definition"),
    variables: set("variable_assignment"),
    moduleUnits: set("command", "pipeline", "list"),
    imports: set("comment"),
    comments: set("comment"),
    identifierTypes: set("variable_name", "word", "command_name"),
    bodyTypes: set("compound_statement", "do_group"),
  },
  c: {
    containers: set(
      "struct_specifier",
      "union_specifier",
      "enum_specifier",
      "type_definition",
    ),
    functions: set("function_definition"),
    variables: set(
      "declaration",
      "field_declaration",
      "enumerator",
      "preproc_def",
      "preproc_function_def",
    ),
    imports: set("preproc_include", "preproc_call"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set(
      "field_declaration_list",
      "compound_statement",
      "enumerator_list",
    ),
  },
  ruby: {
    containers: set("class", "module", "singleton_class"),
    functions: set("method", "singleton_method"),
    variables: set("assignment", "operator_assignment", "alias"),
    moduleUnits: set("call"),
    imports: set(),
    comments: set("comment"),
    identifierTypes: set(
      ...commonIdentifiers,
      "method",
      "constant",
      "instance_variable",
      "class_variable",
      "global_variable",
    ),
    bodyTypes: set("body_statement", "do_block", "block"),
  },
  hcl: {
    containers: set("block"),
    functions: set(),
    variables: set("attribute"),
    imports: set(),
    comments: set("comment"),
    identifierTypes: set("identifier", "get_attr"),
    bodyTypes: set("body"),
  },
  rust: {
    containers: set(
      "struct_item",
      "enum_item",
      "union_item",
      "trait_item",
      "impl_item",
      "mod_item",
      "foreign_mod_item",
    ),
    functions: set("function_item", "function_signature_item"),
    variables: set(
      "const_item",
      "static_item",
      "field_declaration",
      "ordered_field_declaration",
      "enum_variant",
      "let_declaration",
      "associated_type",
      "type_item",
    ),
    moduleUnits: set("macro_definition", "macro_invocation"),
    imports: set(
      "attribute_item",
      "shebang",
      "use_declaration",
      "extern_crate_declaration",
      "inner_attribute_item",
    ),
    comments: set("line_comment", "block_comment"),
    identifierTypes: set(...commonIdentifiers, "scoped_identifier"),
    bodyTypes: set(
      "declaration_list",
      "field_declaration_list",
      "enum_variant_list",
      "block",
    ),
  },
  lua: {
    containers: set(),
    functions: set("function_declaration"),
    variables: set("variable_declaration", "assignment_statement"),
    moduleUnits: set("function_call"),
    imports: set(),
    comments: set("comment"),
    identifierTypes: set(
      "identifier",
      "dot_index_expression",
      "method_index_expression",
    ),
    bodyTypes: set("block"),
  },
  go: {
    containers: set("type_alias", "type_spec"),
    functions: set(
      "function_declaration",
      "method_declaration",
      "method_elem",
      "method_spec",
    ),
    variables: set(
      "const_spec",
      "field_declaration",
      "short_var_declaration",
      "var_spec",
    ),
    imports: set("package_clause", "import_declaration"),
    comments: set("comment"),
    identifierTypes: set(
      ...commonIdentifiers,
      "field_identifier",
      "package_identifier",
    ),
    bodyTypes: set("field_declaration_list", "block"),
  },
  makefile: {
    containers: set("conditional"),
    functions: set(),
    variables: set("variable_assignment", "define_directive"),
    moduleUnits: set("rule"),
    imports: set("include_directive", "vpath_directive"),
    comments: set("comment"),
    identifierTypes: set("word", "variable", "variable_reference"),
    bodyTypes: set("recipes"),
  },
  kotlin: {
    containers: set(
      "class_declaration",
      "object_declaration",
      "companion_object",
      "type_alias",
    ),
    functions: set("function_declaration", "secondary_constructor"),
    variables: set("class_parameter", "property_declaration", "enum_entry"),
    moduleUnits: set("anonymous_initializer"),
    imports: set("package_header", "import_header", "import_list"),
    comments: set("line_comment", "multiline_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("class_body", "function_body", "block"),
  },
  css: {
    containers: set("rule_set", "media_statement", "keyframes_statement"),
    functions: set(),
    variables: set("declaration"),
    imports: set("import_statement"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("block"),
  },
  dart: {
    containers: set(
      "class_definition",
      "enum_declaration",
      "extension_declaration",
      "mixin_declaration",
      "type_alias",
    ),
    functions: set(
      "function_signature",
      "method_signature",
      "getter_signature",
      "setter_signature",
      "constructor_signature",
    ),
    variables: set("declaration", "enum_constant"),
    imports: set(
      "import_or_export",
      "library_name",
      "part_declaration",
      "part_of_declaration",
    ),
    comments: set("comment", "documentation_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("class_body", "function_body", "block"),
  },
  elisp: {
    containers: set(),
    functions: set("function_definition"),
    variables: set("variable_definition", "constant_definition"),
    moduleUnits: set("feature_provide"),
    imports: set("feature_require"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("list"),
  },
  elixir: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set(),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("do_block"),
  },
  elm: {
    containers: set("type_declaration", "type_alias_declaration"),
    functions: set("value_declaration"),
    variables: set("port_annotation"),
    imports: set("module_declaration", "import_clause"),
    comments: set("line_comment", "block_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("let_in_expr", "case_of_expr"),
  },
  embedded_template: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set("directive"),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("code"),
  },
  html: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set("script_element", "style_element"),
    sections: set("element"),
    imports: set("doctype"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("element"),
  },
  json: dataDocumentShape,
  objc: {
    containers: set(
      "class_interface",
      "class_implementation",
      "category_interface",
      "category_implementation",
      "protocol_declaration",
      "struct_specifier",
      "enum_specifier",
    ),
    functions: set(
      "function_definition",
      "method_declaration",
      "method_definition",
    ),
    variables: set("declaration", "field_declaration", "property_declaration"),
    imports: set("preproc_include", "preproc_import"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set(
      "compound_statement",
      "field_declaration_list",
      "implementation_definition",
    ),
  },
  ocaml: {
    containers: set(
      "module_definition",
      "module_type_definition",
      "class_definition",
      "type_definition",
    ),
    functions: set("value_definition"),
    variables: set("external", "instance_variable_definition"),
    imports: set("open_module", "include_module"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("structure", "class_body"),
  },
  ql: {
    containers: set("dataclass", "module"),
    functions: set("predicate", "classlessPredicate"),
    variables: set("select", "moduleMember"),
    imports: set("importDirective"),
    comments: set("lineComment", "blockComment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("moduleBody", "predicateBody"),
  },
  rescript: {
    containers: set(
      "module_declaration",
      "module_type_declaration",
      "type_declaration",
    ),
    functions: set(),
    variables: set("let_declaration"),
    imports: set("open_statement", "include_statement"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("block"),
  },
  scala: {
    containers: set(
      "class_definition",
      "trait_definition",
      "object_definition",
      "enum_definition",
      "type_definition",
    ),
    functions: set("function_definition", "function_declaration"),
    variables: set(
      "val_definition",
      "var_definition",
      "given_definition",
      "enum_case_definitions",
    ),
    imports: set("package_clause", "import_declaration", "export_declaration"),
    comments: set("comment", "block_comment", "line_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("template_body", "block"),
  },
  solidity: {
    containers: set(
      "contract_declaration",
      "interface_declaration",
      "library_declaration",
      "struct_declaration",
      "enum_declaration",
    ),
    functions: set(
      "function_definition",
      "constructor_definition",
      "modifier_definition",
      "fallback_receive_definition",
    ),
    variables: set(
      "state_variable_declaration",
      "event_definition",
      "error_declaration",
      "enum_value",
    ),
    imports: set("import_directive", "pragma_directive"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("contract_body", "function_body", "block_statement"),
  },
  swift: {
    containers: set(
      "class_declaration",
      "struct_declaration",
      "protocol_declaration",
      "enum_declaration",
      "extension_declaration",
      "typealias_declaration",
    ),
    functions: set(
      "function_declaration",
      "initializer_declaration",
      "deinitializer_declaration",
      "subscript_declaration",
    ),
    variables: set(
      "property_declaration",
      "constant_declaration",
      "enum_entry",
    ),
    imports: set("import_declaration"),
    comments: set("comment", "multiline_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("class_body", "function_body", "statements"),
  },
  systemrdl: {
    containers: set("component_named_def", "enum_def", "struct_def"),
    functions: set(),
    variables: set("component_inst", "property_assignment"),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("component_body"),
  },
  tlaplus: {
    containers: set("module"),
    functions: set("operator_definition", "function_definition"),
    variables: set("constant_declaration", "variable_declaration"),
    imports: set("extends", "instance"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("source_file"),
  },
  toml: dataDocumentShape,
  vue: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set("script_element", "template_element", "style_element"),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("element"),
  },
  yaml: dataDocumentShape,
  zig: {
    containers: set(
      "struct_declaration",
      "enum_declaration",
      "union_declaration",
      "opaque_declaration",
    ),
    functions: set("function_declaration"),
    variables: set("variable_declaration", "field_declaration"),
    imports: set(),
    comments: set("line_comment", "doc_comment", "container_doc_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("block"),
  },
  sql: {
    containers: set(
      "create_table",
      "create_view",
      "create_materialized_view",
      "create_type",
      "create_schema",
    ),
    functions: set("create_function", "create_procedure", "create_trigger"),
    variables: set(
      "create_index",
      "create_policy",
      "create_sequence",
      "alter_table",
      "drop_statement",
    ),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("column_definitions", "block"),
  },
  markdown: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set("section"),
    imports: set(),
    comments: set("html_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("document"),
  },
  mdx: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set("section"),
    imports: set("mdx_esm_block"),
    comments: set("html_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("document"),
  },
  dockerfile: {
    containers: set("stage"),
    functions: set(),
    variables: set("arg_instruction", "env_instruction"),
    moduleUnits: set(
      "from_instruction",
      "run_instruction",
      "copy_instruction",
      "add_instruction",
      "cmd_instruction",
      "entrypoint_instruction",
    ),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("source_file"),
  },
  graphql: {
    containers: set(
      "object_type_definition",
      "interface_type_definition",
      "input_object_type_definition",
      "enum_type_definition",
      "union_type_definition",
      "scalar_type_definition",
      "schema_definition",
    ),
    functions: set("operation_definition", "fragment_definition"),
    variables: set("field_definition", "enum_value_definition"),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("fields_definition", "selection_set"),
  },
  prisma: {
    containers: set(
      "model_block",
      "enum_block",
      "type_block",
      "datasource_block",
      "generator_block",
    ),
    functions: set(),
    variables: set("model_field", "enum_value"),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("source_file"),
  },
  protobuf: {
    containers: set("message", "enum", "service", "extend", "group"),
    functions: set("rpc"),
    variables: set("field", "enum_field", "oneof_field", "option"),
    imports: set("syntax", "package", "import"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("message_body", "enum_body", "service_body", "oneof_body"),
  },
  xml: dataDocumentShape,
  scss: {
    containers: set("rule_set", "media_statement", "mixin_statement"),
    functions: set("function_statement", "mixin_statement"),
    variables: set("declaration"),
    imports: set("import_statement", "use_statement", "forward_statement"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("block"),
  },
  svelte: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set("script_element", "style_element", "element"),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("document"),
  },
  astro: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set("frontmatter", "element"),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("document"),
  },
  r: {
    containers: set(
      "s4_class_definition",
      "r6_class_definition",
      "rc_class_definition",
    ),
    functions: set(),
    variables: set("binary_operator"),
    imports: set("namespace_operator"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("braced_expression"),
  },
  julia: {
    containers: set(
      "struct_definition",
      "abstract_definition",
      "primitive_definition",
      "module_definition",
      "macro_definition",
    ),
    functions: set(
      "function_definition",
      "short_function_definition",
      "macro_definition",
    ),
    variables: set(
      "const_statement",
      "assignment",
      "typed_expression",
      "export_statement",
    ),
    imports: set("import_statement", "using_statement"),
    comments: set("line_comment", "block_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("block"),
  },
  haskell: {
    containers: set(
      "data_type",
      "newtype",
      "class",
      "instance",
      "type_synomym",
    ),
    functions: set("function", "signature"),
    variables: set("bind", "pattern_synonym"),
    clausesShareOneDeclaration: true,
    imports: set("header", "import"),
    comments: set("comment", "haddock"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("declarations", "where"),
  },
  clojure: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set(),
    imports: set(),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("list_lit"),
  },
  erlang: {
    containers: set("record_decl", "type_alias"),
    functions: set("fun_decl"),
    variables: set("spec", "callback", "macro_def"),
    imports: set(
      "module_attribute",
      "export_attribute",
      "import_attribute",
      "include_attribute",
      "include_lib_attribute",
    ),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("function_clause", "clause_body"),
  },
  fsharp: {
    containers: set(
      "named_module",
      "type_definition",
      "class_definition",
      "interface_definition",
    ),
    functions: set("function_or_value_defn", "member_defn"),
    variables: set("record_field", "union_case"),
    imports: set("open_statement", "namespace"),
    comments: set("line_comment", "block_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("module_body", "class_body"),
  },
  powershell: {
    containers: set("class_statement", "enum_statement"),
    functions: set("function_statement", "method_statement"),
    variables: set("assignment_expression", "property_statement"),
    imports: set("using_statement", "requires_statement"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("script_block", "statement_block"),
  },
  fortran: {
    containers: set(
      "module",
      "submodule",
      "derived_type_definition",
      "interface",
    ),
    functions: set("function", "subroutine"),
    variables: set("variable_declaration", "parameter_statement"),
    imports: set("use_statement", "include_statement"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("internal_procedures", "translation_unit"),
  },
  perl: {
    containers: set("package_statement", "class_definition"),
    functions: set("function_definition", "method_definition"),
    variables: set(
      "variable_declaration",
      "assignment_expression",
      "constant_declaration",
    ),
    imports: set("use_statement", "require_expression"),
    comments: set("comment", "pod"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("block"),
  },
  groovy: {
    containers: set(
      "class_declaration",
      "interface_declaration",
      "enum_declaration",
      "trait_declaration",
    ),
    functions: set(
      "method_declaration",
      "constructor_declaration",
      "function_declaration",
    ),
    variables: set(
      "field_declaration",
      "variable_declaration",
      "property_declaration",
    ),
    imports: set("package_declaration", "import_declaration"),
    comments: set("line_comment", "block_comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("class_body", "block"),
  },
  nix: {
    containers: set(),
    functions: set("function_expression"),
    variables: set("binding"),
    imports: set("with_expression"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("binding_set", "attrset_expression"),
  },
  latex: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set("chapter", "section", "subsection", "subsubsection"),
    imports: set("package_include", "class_include"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("source_file"),
  },
  systemverilog: {
    containers: set(
      "module_declaration",
      "interface_declaration",
      "program_declaration",
      "class_declaration",
      "package_declaration",
      "checker_declaration",
    ),
    functions: set(
      "function_declaration",
      "task_declaration",
      "constructor_declaration",
    ),
    variables: set(
      "data_declaration",
      "parameter_declaration",
      "net_declaration",
    ),
    imports: set(
      "package_import_declaration",
      "include_compiler_directive",
      "timescale_compiler_directive",
    ),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set(
      "function_body_declaration",
      "task_body_declaration",
      "class_body",
    ),
  },
  assembly: {
    containers: set(),
    functions: set(),
    variables: set(),
    moduleUnits: set("label"),
    imports: set("include"),
    comments: set("comment"),
    identifierTypes: commonIdentifiers,
    bodyTypes: set("program"),
  },
};
